# Generated by Django 5.0 on 2025-01-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akcel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
