# Generated by Django 5.0 on 2025-01-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akcel', '0002_campaign_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='citizenship_photo',
            field=models.ImageField(blank=True, null=True, upload_to='citizenship_photos/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='payment_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
