# Generated by Django 5.0 on 2025-01-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akcel', '0003_campaign_additional_info_campaign_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='payment_info',
        ),
        migrations.AddField(
            model_name='campaign',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='QR_CODES/'),
        ),
    ]
