# Generated by Django 5.0 on 2025-01-24 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akcel', '0004_remove_campaign_payment_info_campaign_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='akcel.category'),
        ),
    ]
