# Generated by Django 5.0 on 2025-02-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akcel', '0005_alter_campaign_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='days_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='progress',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
