# Generated by Django 5.0 on 2025-02-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akcel', '0006_campaign_days_left_campaign_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donated_at',
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(default='temporary_value', max_length=255),
        ),
        migrations.AlterField(
            model_name='donation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
