# Generated by Django 5.0 on 2025-02-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akcel', '0007_alter_campaign_is_active'),
        ('akcel', '0007_remove_donation_donated_at_donation_transaction_id_and_more'),
    ]

    operations = [
    ]
